### ISSUE TITLE
Zabbix Template Import error

### ISSUE THREAD

**Issue by martinvandiemen** [anapsix/zabbix-haproxy#13]
Importing the "haproxy_zbx_template.xml" template into Zabbix (3.0.1) results in the following error:
`Invalid XML tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "filter" is missing.`

Would be great if this template could also bee used in Zabbix 3.0.

Thanks!

**Comment by martinvandiemen** [comment]
Filters were in a comment. Removed comment, solved.

**Comment by anapsix** [comment]
Glad to hear it works with Zabbix 3.0

**Comment by afkpaul** [comment]
Migration from Zabbix 3.4 to Zabbix 3.2 -->

echo "#!/bin/bash
replace "<version>3.4</version>" "<version>3.2</version>" -- $1
replace "<snmp_community/>" "<snmp_community/><multiplier>0</multiplier>" -- $1
replace "<snmpv3_contextname/>" "<snmpv3_contextname/><delta>0</delta>" -- $1
replace "<snmpv3_privpassphrase/>" "<snmpv3_privpassphrase/><formula>1</formula>" -- $1
replace "<ipmi_sensor/>" "<ipmi_sensor/><data_type>0</data_type>" -- $1
grep preprocessing $1 " > a

./a template.xml

if                     <preprocessing> or <preprocessing/> tags appear, please remove them from the .xml (and remove content inside the tags)
_Be aware to manually add on **Use custom multiplier** and **Store as** values from these tags_

**Comment by pasechnik2307** [comment]
Hello! Does correct works Discovery on zabbix 3.4?
