### ISSUE TITLE
Error importing template in Zabbix 3.0 - SOLVED

### ISSUE THREAD

**Issue by zilmarr** [anapsix/zabbix-haproxy#14]
Hey guys!

I'm getting this error when I try to import the template in Zabbix 3.0:

```
"Invalid XML tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "filter" is missing."
```

Any thoughts?

**Comment by zilmarr** [comment]
Sorry! There was already a closed issue about it.

**Comment by zilmarr** [comment]
[haproxy_zbx_template.zip](https://github.com/anapsix/zabbix-haproxy/files/172880/haproxy_zbx_template.zip)

**Comment by plutoid** [comment]
could you import this template file to repo and change its name like haproxy_zbx_template_zbx3.zip?

best regards

**Comment by plutoid** [comment]
hope owner know this. :P

**Comment by anapsix** [comment]
commit 09fa1865f takes care of that, thanks for the suggestion
