### ISSUE TITLE
Discovery rules not working

### ISSUE THREAD

**Issue by sanderse** [anapsix/zabbix-haproxy#17]
Hi! 
I've configured according to your instructions. Manually created items retrive data from HAProxy as expected. But discovery rules doesn't seem to work.

Template is imported and assigned to Host, but descovery rules gets status "Not supported" and "Value should be a JSON object" as info message.
Both zabbix-server and zabbix-agent is v3.0.2

Any input on how to solve this without manually creating all applications/items/triggers and graphs?

Thanks!

**Comment by noamik** [comment]
You should try to run the discovery manually and look into the return values. It looks like the discovery script is failing and returning an error instead of proper JSON data.
The header of haproxy_discovery.sh explains how to run the script.

**Comment by sanderse** [comment]
Hi! Thanks for your feedback.
Running those commands returns data like expected - from my point of view.

Like this: sudo sh /usr/local/bin/haproxy_discovery.sh FRONTEND returns
-e {
        "data":[
                {
                        "{#FRONTEND_NAME}":"stats"},
                {
                        "{#FRONTEND_NAME}":"static"},
                {
                        "{#FRONTEND_NAME}":"www"}]}

**Comment by noamik** [comment]
It's either an issue with access rights to the socket using the zabbix_agent or with the configuration of the haproxy socket macro (https://github.com/anapsix/zabbix-haproxy/blob/master/haproxy_zbx_template.xml#L8597). Make sure the pathes in the macro match the pathes on your machine. If they do, try to get the values for a specific frontend or a discovery result through zabbix_get and/or zabbix_agentd.

See: https://www.zabbix.com/documentation/3.0/manual/concepts/agent
https://www.zabbix.com/documentation/3.0/manual/concepts/get for details.

For an end to end test, run zabbix_get on the server using the proper discovery targets (example: "haproxy.list.discovery[{$HAPROXY_SOCK},BACK]" or "haproxy.stats[{$HAPROXY_SOCK},{#FRONTEND_NAME},FRONTEND,status]"  ). You might want to start with local zabbix_agentd calls first for easier debugging.
