### ISSUE TITLE
Import error with zabbix 3 and xml template

### ISSUE THREAD

**Issue by marianov** [anapsix/zabbix-haproxy#22]
This error shows up when importing the xml file into zabbix 3 :
Invalid XML tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "filter" is missing.

**Comment by anapsix** [comment]
See "filter" issue in previously reported..

**Comment by anapsix** [comment]
https://github.com/anapsix/zabbix-haproxy/issues/13

**Comment by anapsix** [comment]
I assume you found it
