### ISSUE TITLE
Fixed some more cases where data was unavailable

### ISSUE THREAD

**Issue by klaasjan** [anapsix/zabbix-haproxy#26]
Please see my new pull request. Code has been stable for 12h for me ;)

Got a suggestion from a collegue who mentioned it should be possible to use zabbix active monitoring where the agent initiates collecting instead of using the parallel zabbix initiated collecting.

Maybe a fix to the template could be made to not ring all the alarms when there's no data available...

**Comment by anapsix** [comment]
Shame on me for not noticing the spacing around "=" (assignment).. thanks to @pokab for fixing it..
Not sure how it's "been stable for 12h" for you.
But, all well that ends well.

**Comment by klaasjan** [comment]
Ouch. Fixed that one after copying it from my local editor to the server. Excuses...

**Comment by anapsix** [comment]
all good
