### ISSUE TITLE
Template does not import into Zabbix 3.2

### ISSUE THREAD

**Issue by mtxd** [anapsix/zabbix-haproxy#30]
Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "filter" is missing.

**Comment by anapsix** [comment]
See #13
Feel free to submit a PR with template version for Zabbix 3.x

**Comment by mtxd** [comment]
A hub owner is not going to test and adapt it to the latest version of zabbix?

**Comment by anapsix** [comment]
3.x introduced new required field - filter, incompatible with 2.x 
I suppose, version 3.x is mature enough to assume most use it and it's time to uncomment "filter" tag 3.x requires.
.. however, don't you take that tone with me, mister

**Comment by anapsix** [comment]
commit 09fa186 takes care of that, thanks for the suggestion
