### ISSUE TITLE
Issue on discovery

### ISSUE THREAD

**Issue by jdecalog** [anapsix/zabbix-haproxy#31]
Everything works fine except the discovery, items are not created in zabbix.
The scripts runs correctly on CLI =>

> zabbix_agentd -t haproxy.list.discovery[SERVER]
haproxy.list.discovery[SERVER]                [t|{
        "data":[
                {
                        "{#BACKEND_NAME}":
[...]

The script for stats work fine too

> /usr/local/bin/haproxy_stats.sh

 

> /run/haproxy/admin.sock backendname BACKEND hrsp_2xx

> 68

The discovery interval is set to 1, is there a way to debug this?

**Comment by noamik** [comment]
Have you tried running the discovery command from cli from your zabbix server using zabbix_get? Most obscure problems I encounter can be found and resolved when seeing a difference in behavior between zabbix_agentd and zabbix_get. Only once zabbix_agentd and zabbix_get return the same result I would look into the scripts data or the template:
https://www.zabbix.com/documentation/1.8/manual/processes/zabbix_get

**Comment by nicoinfra** [comment]
Hello, I've ran this problem. Adjusting the stats socket to
`stats socket /etc/haproxy/haproxysock level user mode 666`

Fixed the problem.

**Comment by anapsix** [comment]
@jdecalog: does @nicoinfra's suggestion take care of your issue?

**Comment by ErrorProne** [comment]
@jdecalog I had to install socat to get results back
