### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Bdelmedico** [anapsix/zabbix-haproxy#32]
Hello guys...

my discovery is not working

1479:20161109:175911.674 item "lb-web-02:haproxy.list.discovery[{$HAPROXY_SOCK},BACK]" became not supported: Unsupported item key.
  1482:20161109:175912.677 item "lb-web-02:haproxy.list.discovery[{$HAPROXY_SOCK},FRONT]" became not supported: Unsupported item key.
  1480:20161109:175913.678 item "lb-web-02:haproxy.list.discovery[{$HAPROXY_SOCK},SERVER]" became not supported: Unsupported item key.

**Comment by Bdelmedico** [comment]
root@lb-web-02:~# sudo zabbix_agentd -t haproxy.list.discovery[FRONT]
haproxy.list.discovery[FRONT]                 [t|{
    "data":[

```
    {
        "{#FRONTEND_NAME}":"Front_Status"},
    {
        "{#FRONTEND_NAME}":"Front_WEB_SLL_GERAL"},
    {
        "{#FRONTEND_NAME}":"Front_WEB_SLL_EV"},
    {
        "{#FRONTEND_NAME}":"Front_WEB_NEW_EV"}]}]
```

**Comment by Bdelmedico** [comment]
root@zabbix:~# zabbix_get -s 10.10.10.85 -k "haproxy.list.discovery[/var/run/haproxy/info.sock,BACKEND]"
ZBX_NOTSUPPORTED: Unsupported item key.

**Comment by Bdelmedico** [comment]
debug zabbix agent

 12698:20161110:102912.686 __zbx_zbx_setproctitle() title:'active checks #1 [idle 1 sec]'
 12697:20161110:102912.796 __zbx_zbx_setproctitle() title:'listener #3 [processing request]'
 12697:20161110:102912.796 Requested [haproxy.list.discovery[/var/run/haproxy/info.sock,FRONTEND]]
 12697:20161110:102912.796 In zbx_popen() command:'/usr/local/bin/haproxy_discovery.sh /var/run/haproxy/info.sock FRONTEND'
 12697:20161110:102912.797 End of zbx_popen():8
 12813:20161110:102912.797 zbx_popen(): executing script
 12697:20161110:102912.804 In zbx_waitpid()
 12697:20161110:102912.805 zbx_waitpid() exited, status:0
 12697:20161110:102912.805 End of zbx_waitpid():12813
 12697:20161110:102912.805 EXECUTE_STR() command:'/usr/local/bin/haproxy_discovery.sh /var/run/haproxy/info.sock FRONTEND' len:14 cmd_result:'{
    "data":[
]}'
 12697:20161110:102912.805 Sending back [{
    "data":[
]}]
 12697:20161110:102912.805 __zbx_zbx_setproctitle() title:'listener #3 [waiting for connection]'
 12693:20161110:102913.684 __zbx_zbx_setproctitle() title:'collector [processing data]'

**Comment by anapsix** [comment]
make sure to confirm that your haproxy is listening on `/var/run/haproxy/info.sock` and has appropriate permissions (so that zabbix user can read/write from/to it)

**Comment by anapsix** [comment]
cleaning up & closing
