### ISSUE TITLE
Invalid tag when importing into Zabbix 3.2 Server

### ISSUE THREAD

**Issue by ghost** [anapsix/zabbix-haproxy#33]
Hi There,

When importing the zabbix template into a Zabbix 3.2 server we get the following error FYI:

Invalid tag "/zabbix_export/templates/template(1)/discovery_rules/discovery_rule(1)": the tag "filter" is missing.

Thanks

**Comment by noamik** [comment]
https://github.com/anapsix/zabbix-haproxy/issues/13

**Comment by anapsix** [comment]
09fa1865f takes care of that
