### ISSUE TITLE
Can't see discovered items

### ISSUE THREAD

**Issue by akshays958** [anapsix/zabbix-haproxy#38]
i can see logs in HA_PROXY application.. but discovery rules don't seem to be working . No items have been added to backend  or frontend applications even after reducing discovery rule timing to 5 mins. 
Where should I place docker_stats.sh file
I tested both the scripts with examples and they all work fine.. but data is not shown on zabbix ..
please reply ASAP.

Thanks

**Comment by anapsix** [comment]
try running discovery script manually as zabbix user on the node with haproxy..
if you are getting data, slow down and go over everything once more.. try Zabbix server debugging output.. or zabbix-get
If not [getting data] - start verifying permissions on the haproxy info socket, remember, Zabbix runs as a separate user

**Comment by NiwanetSupport** [comment]
Hi! I'm also concerned by this issue.
With the command: `sudo -u zabbix zabbix_agentd -t 'haproxy.list.discovery[SERVERS]'`
I'm getting datas, it's working.
However I don't know why there is no discovered hosts on my Zabbix server.
What do you mean by "try Zabbix server debugging output or zabbix-get" ?
I'm running out of ideas.

Thanks

**Comment by anapsix** [comment]
@Niwanet, zabbix agent/server has debug, afaik, log level.. it spits out a lot of info.. it might help debug the issue.
you could adjust your discovery interval, so it runs more often and is easier to catch

**Comment by anapsix** [comment]
@akshays958, perhaps your problem is similar to @Niwanet's
where zabbix user did not have required binaries in the path..
make sure zabbix user has all the required binaries (such as nc / socat) in PATH
(e.g include /bin and /sbin in PATH)

**Comment by NiwanetSupport** [comment]
I added zabbix to root and haproxy groups.
I installed netcat.
Now I get this message in zabbix server: 
14679:20170913:163438.838 item "Cem-db-front:haproxy.stats[{$HAPROXY_SOCK},galera,db3,smax]" became supported
Which is great, and I also get data 👍 
That is a hug step forward, thanks!

But shouldn't I see new hosts appeared?

**Comment by anapsix** [comment]
You probably should not add Zabbix user to root group.
But rather, update your `/etc/bash.bashrc` (or similar) to include proper PATH

**Comment by anapsix** [comment]
Well.. it's been awhile since I've used it myself.. so I don't quite remember, but there might not be hosts.. rather items under whatever host haproxy is running on

**Comment by NiwanetSupport** [comment]
On RHEL7, I guess it's the /etc/bashrc file, but I don't know what to modify inside this file in order to include the PATH.

You are right, now I have to find a way to send an alert if the servers detected by the discovery are DOWN.

**Comment by NiwanetSupport** [comment]
Everything is done, Thanks a lot! Miraculous script! Thanks a lot for your help @anapsix  👍

**Comment by anapsix** [comment]
cleaning up & closing
