### ISSUE TITLE
error getting values

### ISSUE THREAD

**Issue by LGprodigy** [anapsix/zabbix-haproxy#39]
31137:20170525:233440.433 error reason for "HOSTNAME:haproxy.stats[{$HAPROXY_SOCK},static,SERVERNAME,smax]" changed: Received value [which: no nc in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)3] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

It makes the values look like this in zabbix server
https://i.gyazo.com/94201887374e6373e32673302026d84b.png

**Comment by anapsix** [comment]
Well, you gonna need to install "nc" (netcat)

**Comment by LGprodigy** [comment]
I was going to respond with I did install it... but then re reading the error it hit me like a bag of bricks... it needed to be installed on the agent server. My apologies!

**Comment by anapsix** [comment]
:) no worries
