### ISSUE TITLE
After restart server, the directory "/var/run/haproxy" is removed.

### ISSUE THREAD

**Issue by dkhromenko** [anapsix/zabbix-haproxy#40]
System - Oracle Linux 7.2/7.3,
after restart OS, the directory "/var/run/haproxy" is removed.
As a result, the haproxy doesn't start - 
"haproxy-systemd-wrapper [2655]: [ALERT] 198/015724 (2656): Starting frontend GLOBAL: can't bind UNIX socket [/var/run/haproxy/info.sock]"
It may make sense to change the default path to the socket "/var/**lib**/haproxy/info.sock" instead of
"/var/**run**/haproxy/info.sock" ?

**Comment by noamik** [comment]
You can put the socket where ever you want it to be. There is a parameter in the template for its location which you can adjust on your zabbix server.

**Comment by dkhromenko** [comment]
That's exactly what I did.
I say that it might make sense to change the default path to lib instead of run?

**Comment by anapsix** [comment]
I realize some distributions might not have that dir, yet it makes more sense to store sockets in `/var/run/`
Unfortunately, there is no definitive place that would be default for all installs.
