### ISSUE TITLE
Update: I do have more or less my hosts

### ISSUE THREAD

**Issue by NiwanetSupport** [anapsix/zabbix-haproxy#41]
I ran zabbix server logs:
error reason for "Cem-db-front:haproxy.stats[{$HAPROXY_SOCK},galera,BACKEND,scur]" changed: Value "which: no nc in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin)
0" of type "string" is not suitable for value type "Numeric (unsigned)"

What should I do?

Zabbix: 3.4

**Comment by anapsix** [comment]
you should install NC aka netcat
(if it's installed, make sure to fix path for zabbix user.. since it does not appear to include `/bin` and `/sbin`)
