### ISSUE TITLE
zabbix user doesn't have enough permission to run the scripts

### ISSUE THREAD

**Issue by angeloudy** [anapsix/zabbix-haproxy#43]
The first error I got is "

   ERROR: cannot find socat binary

"
Then I hardcoded the line
SOCAT_BIN="/usr/local/bin/socat"

And then I got another error: ERROR: haproxy socket is not writable

So zabbix is checking if /var/run/haproxy.sock exists and returned false.

**Comment by anapsix** [comment]
Make sure you configure it to use the appropriate path to haproxy socket and set permissions on it as described in the readme

**Comment by anapsix** [comment]
Example:
```
stats socket /var/run/haproxy/info.sock  mode 666 level user
```

**Comment by anapsix** [comment]
going it assume it worked out
