### ISSUE TITLE
Active version of the v3 template

### ISSUE THREAD

**Issue by binary64** [anapsix/zabbix-haproxy#44]
Hi,

How can we make the zabbix v3 template active?

Many thanks inadvance

**Comment by anapsix** [comment]
@binary64, you can select the template items, after you've imported them, and using Mass Update, change the `Type` to `Zabbix agent (active)`

**Comment by binary64** [comment]
yes, but the Item Prototypes are still non-Active. And there isn't an option in the UI to Mass Update those. Only mass 'Create enabled' and 'Create disabled' function.

**Comment by anapsix** [comment]
Then, one could change a type in template from 0, to 1, I suspect.
You could experiment with one of them, by changing it manually, then exporting to template and checking resulting xml.
