### ISSUE TITLE
Issue with discovery (Again)

### ISSUE THREAD

**Issue by ficofer** [anapsix/zabbix-haproxy#47]
I have read and check all the closes issues.

I know this is a recurrent problem or question, so thanks for reading and trying to help.

I am working in the SAME vlan, some servers get discover and some not. Same configuration is installed in all of them *with ansible playbook*

The servers that do not auto-discovery the HAproxy plugin, do show up and show other server stats in zabbix.

I have checked permissions, socket, install binaries and they are equal.

I have the same version of agents against the same server (3.0.15)

I am running out of options in how to debug, I could not find zabbix_get binary in my server, and local commands as queries to the socket works perfectly in the clients.

The issue is that this discovery rules never happen and never show up for this clients but they do for the rest.

```
HAProxy: HAProxy backend discovery	Item prototypes 42	Trigger prototypes	Graph prototypes 34	Host prototypes	haproxy.list.discovery[{$HAPROXY_SOCK},BACKEND]	1m	Zabbix agent (active)	Enabled	
	HAProxy: HAProxy frontend discovery	Item prototypes 28	Trigger prototypes	Graph prototypes 20	Host prototypes	haproxy.list.discovery[{$HAPROXY_SOCK},FRONTEND]	1m	Zabbix agent (active)	Enabled	
	HAProxy: HAProxy server discovery	Item prototypes 48	Trigger prototypes	Graph prototypes 34	Host prototypes	haproxy.list.discovery[{$HAPROXY_SOCK},SERVER]	1m	Zabbix agent (active)	Enabled
```

Some servers get around 7xx of graphs and this only 9 due to the lack of discovery.

PLUS.

In latest data I see basic info about the not discovered servers from HA proxy such us:

```
HAProxy (3 Items)
--
  |   | HAProxy config file checksum (/etc/haproxy/haproxy.cfg) | 2018-03-28 10:10:36 | 3248702632 |   | Graph
  |   | HAProxy memory used | 2018-03-28 10:15:34 | 298 Mb |   | Graph
  |   | HAProxy number of running processes | 2018-03-28 10:18:35 | 1 |   | Graph
```

@anapsix your input will be really value in this.

**Comment by ficofer** [comment]
@anapsix This is the *only* error I am able to spot in the logs:

```
 15977:20180328:222007.041 Requested [haproxy.list.discovery[{$HAPROXY_SOCK},SERVER]]
 15977:20180328:222007.041 Sending back [ZBX_NOTSUPPORTED: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.]
 15975:20180328:222007.060 Requested [proc.num[haproxy]]
 15976:20180328:222013.247 Requested [haproxy.list.discovery[{$HAPROXY_SOCK},BACK]]
 15976:20180328:222013.247 Sending back [ZBX_NOTSUPPORTED: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.]
 15976:20180328:222014.268 Requested [haproxy.list.discovery[{$HAPROXY_SOCK},FRONT]]
 15976:20180328:222014.268 Sending back [ZBX_NOTSUPPORTED: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.]
 15975:20180328:222106.880 Requested [proc.num[haproxy]]
 15976:20180328:222106.881 Requested [haproxy.list.discovery[{$HAPROXY_SOCK},SERVER]]
 15976:20180328:222106.881 Sending back [ZBX_NOTSUPPORTED: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.]
 15977:20180328:222207.008 Requested [proc.num[haproxy]]
```

```
  4123:20180328:221735.264 item "prod-lb01:haproxy.list.discovery[{$HAPROXY_SOCK},SERVER]" became not supported: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.
  4122:20180328:221741.598 item "prod-lb01:haproxy.list.discovery[{$HAPROXY_SOCK},BACK]" became not supported: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.
  4122:20180328:221742.603 item "prod-lb01:haproxy.list.discovery[{$HAPROXY_SOCK},FRONT]" became not supported: Special characters "\, ', ", `, *, ?, [, ], {, }, ~, $, !, &, ;, (, ), <, >, |, #, @, 0x0a" are not allowed in the parameters.
  4123:20180328:222036.445 item "prod-lb01:vfs.file.cksum[{$HAPROXY_CONFIG}]" became not supported: Cannot open file: [2] No such file or directory

```

**Comment by ficofer** [comment]
I have find out that zabbix_get from the zabbix server to the not discovering client is throwing no front or backs or servers at all... thats why is not discovering... but I am not able to find out the why of this, configurations in both clients are EQUAL.

```
zabbix_get -s 192.168.41.51 -p 10050 -k haproxy.list.discovery[/var/run/haproxy/info.sock,SERVER]
{
	"data":[
]}
#  zabbix_get -s 192.168.48.51 -p 10050 -k haproxy.list.discovery[/var/run/haproxy/info.sock,SERVER]
{
	"data":[

		{
			"{#BACKEND_NAME}":"bk_https_web",
			"{#SERVER_NAME}":"prod-app01"},
		{
			"{#BACKEND_NAME}":"bk_https_web",
			"{#SERVER_NAME}":"prod-app02"},
		{
			"{#BACKEND_NAME}":"bk_https_web",
			"{#SERVER_NAME}":"prod-app03"},
		{
			"{#BACKEND_NAME}":"bk_https_web",
			"{#SERVER_NAME}":"prod-app04"},
```

**Comment by pasechnik2307** [comment]
I have the same problem, but in my case I can't use sudo( 

zabbix_get -s X.X.X.X -p 10050 -k haproxy.stats[/var/run/haproxy/info.sock,cloud,FRONTEND,bin]
/usr/local/bin/haproxy_stats.sh: line 179: /var/tmp/haproxy_stats.cache.lock: Permission denied

**Comment by sampy12345** [comment]
Hi All,

Is the above one fixed for anyone. I am also facing same problem

**Comment by trongthongvo** [comment]
Hi All, 

I have issue same above. Status HAProxy, HAProxy Backend, HAProxy Backend Server, HAProxy Frontend is enable. But only HAProxy with items (HAProxy config file checksum, HAProxy memory used, HAProxy number of running processes) is working get data on Zabbix

HAProxy Backend, HAProxy Backend Server, HAProxy Frontend can't get data on Zabbix.

**Comment by anapsix** [comment]
@trongthongvo, see if solution described in https://github.com/anapsix/zabbix-haproxy/issues/55 helps

**Comment by trongthongvo** [comment]
Thanks @anapsix. I fixed success.

**Comment by anapsix** [comment]
@trongthongvo, was it an issue with permissions, or SELinux?

**Comment by trongthongvo** [comment]
@anapsix I set both. after edit, it's working.

**Comment by anapsix** [comment]
added a note about SELinux to the [Troubleshooting](../#troubleshooting)
