### ISSUE TITLE
Unsupported item key, how to give zabbix agent right permission for admin socket ?

### ISSUE THREAD

**Issue by khurshid-alam** [anapsix/zabbix-haproxy#53]
We are running zabbix 4.x on Ubuntu 18.04 LTS and ee have 

`stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners`

in `/etc/haproxy.cfg `

and it's not getting any data.

`/usr/local/bin/haproxy_discovery.sh /run/haproxy/admin.sock FRONTEND`

gives

```json
{
	"data":[]
}
```
From zabbix servers log,

`25545:20191009:175038.809 item "lb:haproxy.list.discovery[{$HAPROXY_SOCK},SERVER]" became not supported: Unsupported item key.
`

Will changing the permission to **666** work ?

**Comment by anapsix** [comment]
by default `HAPROXY_SOCK="/var/run/haproxy/info.sock"`
make sure to set it to what you are using

**Comment by anapsix** [comment]
also manually check you are able to see the output returned from a socket
```
echo "show stat" | socat ${HAPROXY_SOCK} stdio
```

**Comment by khurshid-alam** [comment]
> by default HAPROXY_SOCK="/var/run/haproxy/info.sock"

I changed this in userparameter_haproxy.conf & haproxy_discovery.sh. Wouldn't that be enough ?

**Comment by khurshid-alam** [comment]
> echo "show stat" | socat ${HAPROXY_SOCK} stdio

socat[28984] E exactly 2 addresses required (there are 1); use option "-h" for help

**Comment by anapsix** [comment]
using an `alpine:3.9` docker image to test.. seems to work
```
docker run -it --rm alpine:3.9 sh
apk add --no-cache haproxy socat
haproxy -f /etc/haproxy/haproxy.cfg
echo "show stat"| socat /var/lib/haproxy/stats stdio
```

**Comment by anapsix** [comment]
in your case, the test would be
```
echo "show stat" | socat /run/haproxy/admin.sock stdio
```

**Comment by khurshid-alam** [comment]
I had to use sudo before socat...may that's the issue

>echo "show stat" | sudo socat /run/haproxy/admin.sock stdio

triad08,BACKEND,0,0,29,865,1000,6305285,7230104145,136020752981,0,0,,1276,150,795,0,UP,1,1,0,,4,9562,66,,1,11,0,,6298374,,1,22,,278,,,,0,6292724,0,8315,4095,32,,,,6305166,252,32,0,0,0,0,0,,,0,0,2349,3188,,,,,,,,,,,,,,http,roundrobin,,,,,,,
zabbix,zabbix,0,0,0,12,,365211,290650209,6490147956,,0,,0,0,0,0,UP,1,1,0,0,0,795434,0,,1,12,1,,365211,,2,1,,19,L4OK,,3,0,363297,1833,2,0,0,,,,,0,0,,,,,0,,,0,2,62,7045,,,,Layer4 check passed,,2,3,4,,,,88.198.203.19:60802,,http,,,,,,,,
zabbix,BACKEND,0,0,0,12,1000,365211,290650209,6490147956,0,0,,0,0,0,0,UP,1,1,0,,0,795434,0,,1,12,0,,365211,,1,1,,19,,,,0,363297,1833,2,0,0,,,,365132,0,0,0,0,0,0,0,,,0,2,62,7045,,,,,,,,,,,,,,http,roundrobin,,,,,,,
default,hub-05,0,0,32,830,,4674906,3144067645,63693653842,,0,,265,289,795,0,UP,1,1,0,12,4,9563,0,,1,13,1,,4673811,,2,19,,277,L4OK,,0,1256600,4576972,0,92659,3799,0,,,,,9394,12,,,,,0,,,0,1,2628,4650,,,,Layer4 check passed,,2,3,4,,,,195.201.105.147:80,,http,,,,,,,,
default,hub-06,0,0,36,843,,4675095,3144502396,63233062666,,0,,303,359,909,0,UP,1,1,0,12,4,9563,0,,1,13,2,,4673882,,2,20,,277,L4OK,,0,1255999,4579682,0,93001,621,0,,,,,9759,23,,,,,0,,,0,0,2169,4188,,,,Layer4 check passed,,2,3,4,,,,195.201.63.31:80,,http,,,,,,,,
default,BACKEND,0,0,68,1347,1000,9349159,6288922326,126926899901,0,0,,1429,648,1704,0,UP,2,2,0,,3,9563,34,,1,13,0,,9347693,,1,39,,554,,,,0,9156654,0,185754,6462,50,,,,9348920,19154,35,0,0,0,0,0,,,0,1,2649,4548,,,,,,,,,,,,,,http,roundrobin,,,,,,,

**Comment by anapsix** [comment]
you are on the right path, try the same command as zabbix agent user

**Comment by khurshid-alam** [comment]
I now have added zabbix user to haproxy group. Still no data...Can't really change to zabbix user since it is system user and shell is  /bin/false

**Comment by khurshid-alam** [comment]
I have now changed it to `/var/run/haproxy.sock` since `/run` is not world readable but `/var` is. And now it shows data  

`/usr/local/bin/haproxy_discovery.sh /var/run/haproxy.sock SERVERS`

```
/var/run/haproxy.sock SERVERS
{
	"data":[

		{
			"{#BACKEND_NAME}":"stats",
			"{#SERVER_NAME}":"FRONTEND"},
		{
			"{#BACKEND_NAME}":"hub_check",
			"{#SERVER_NAME}":"hub-check"},
		{
			"{#BACKEND_NAME}":"sandbox_v3",
			"{#SERVER_NAME}":"sandbox"},
		{
			"{#BACKEND_NAME}":"default",
			"{#SERVER_NAME}":"hub-06"}]}
```

But it is still not show on zabbix ui. Do I need to re-import the template from zabbix ui ?

Edit: In the ui only memory used, running processes showing but not anything else (FRONTEND, BACKEND).

![image](https://user-images.githubusercontent.com/1333217/66565943-53c15b00-eb81-11e9-84d7-946ac8aca5e0.png)


However they are available under discovery rules.  

@anapsix  ?

**Comment by anapsix** [comment]
you shouldn't need to reimport the template
just make sure to check if zabbix user can run those commands (access the haproxy socket, write cache file, etc)
even if zabbix user doesn't have a shell, you can still run commands as that user
for example:
```
docker run -it --rm alpine:3.9 sh
/ # adduser -S zabbix-agent
/ # id zabbix-agent
uid=100(zabbix-agent) gid=65533(nogroup) groups=65533(nogroup),65533(nogroup)
/ # grep zabbix /etc/passwd
zabbix-agent:x:100:65533:Linux User,,,:/home/zabbix-agent:/sbin/nologin
/ # su zabbix-agent -s /bin/sh -c 'whoami'
zabbix-agent
/ # su zabbix-agent -s /bin/sh -c 'touch /tmp/hello'
/ # ls -la /tmp/hello
-rw-r--r--    1 zabbix-a nogroup          0 Oct 15 16:57 /tmp/hello
```

**Comment by AlexeyVshk** [comment]
I've used /var/run/haproxy/info.sock .So, It works w/o issues.DONE!
I'd like to change to --> /var/lib/haproxy/stats 
I've changed the scripts haproxy_discovery.sh and haproxy_stats.sh.
After changing, I can see the same mistake every time -->  ERROR:haproxy socket is not writable 
So, what the root of the problem ? What must be changed to keep working with /var/lib/haproxy/stats

**Comment by anapsix** [comment]
@AlexeyVshk, make sure the permissions on the socket, and **directories where it's located** are appropriate for the user running the check (`zabbix-agent`, or whatever it is on your system)
Using `/var/lib/haproxy/stats` as example: if `/var`, and `/var/lib` are owned by "root", but typically have execute and read bits set for "others" (`0755`), make sure `/var/lib/haproxy` directory is also `0755`.

**Comment by anapsix** [comment]
checkout a note about SELinux in [Troubleshooting](../#troubleshooting), and https://github.com/anapsix/zabbix-haproxy/issues/55
