### ISSUE TITLE
Error & solution

### ISSUE THREAD

**Issue by nabilmamori** [anapsix/zabbix-haproxy#55]
Error n° 1: `/usr/local/bin/haproxy_stats.sh:line179:/var/tmp/haproxy_stats.cache.lock: Permission denied
`
Solution:  `chmod 646 /var/tmp/haproxy_stats.cache.lock
`
Error n° 2:`/usr/local/bin/haproxy_stats.sh:line179:/var/tmp/haproxy_stats.cache: Permission denied`
Solution:  `chmod 646 /var/tmp/haproxy_stats.cache`

Error n° 3: `haproxy socket is not writable`
Solution:  `setenforce 0` ( selinux disabled)

**Comment by anapsix** [comment]
thanks fort the tip, added a note about SELinux to the [Troubleshooting](../#troubleshooting)
