### ISSUE TITLE
Metrics disappear from time to time

### ISSUE THREAD

**Issue by arys0685** [anapsix/zabbix-haproxy#56]
From the moment we updated haproxy to version 2.1.3 and started using nbthreads, they periodically began to receive bad frontend_name / FRONTEND / BACKEND and no-items in zabbix.
The configuration of the scripts for userparameters_haproxy.conf did not change, only the parameters nbproc and nbthreads changed in haproxy.cfg. During the search for the causes, it was found that "haproxy" socket sometimes is empty.
Have you encountered such a problem?

**Comment by arys0685** [comment]
### haproxy global
global
    stats socket /var/lib/haproxy/info.sock mode 666 level user 
    log 127.0.0.1 local0
    log 127.0.0.1 local1 notice
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    user postgres
    group postgres
    daemon
    maxconn 2000
    nbproc 1
    nbthread 4
    cpu-map auto:1/1-4 0-3
    stats bind-process 1
In haproxy_discovery.sh and haproxy_stats.sh --  /var/lib/haproxy/info.sock

**Comment by anapsix** [comment]
afaik, separate threads have separate stats
see if you can bind a specific thread to specific stats socket

**Comment by arys0685** [comment]
Perhaps you are confused with process monitoring?

**Comment by anapsix** [comment]
yep, I was thinking of processes, not threads

**Comment by arys0685** [comment]
but we use nbproc 1...
