### ISSUE TITLE
Deps check

### ISSUE THREAD

**Issue by ghost** [anapsix/zabbix-haproxy#7]
Can you please add check for required tools?

For example:
If socat is not installed/available - return to zabbix server some special error.

**Comment by anapsix** [comment]
It will be included in upcoming update.

**Comment by anapsix** [comment]
@tylkas, I've added a check for `socat` in today's updates.
There is no checks for `tr`, `grep`, `cut`, since these are base tools expected to be present on every system. Let me know if you encounter systems without any of these tools and I'll add the check.
Cheers!

**Comment by ghost** [comment]
@anapsix thank you a lot. It will help to avoid no data without errors in big datacenters.
